/*
 * This source file was generated by the Gradle 'init' task
 */
package me.eeshe.watchfacescraper;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
    // SQLiteManager sqLiteManager = new SQLiteManager();
    // WatchfaceService watchfaceService = new WatchfaceService(sqLiteManager);
    // watchfaceService.createTables();
    //
    // List<Watchface> watchfaces = new FaceAppsScraper().scrape();
    // watchfaceService.writeWatchfaces(watchfaces);
  }
}
