/*
 * This source file was generated by the Gradle 'init' task
 */
package me.eeshe.watchfacescraper;

import me.eeshe.watchfacescraper.model.scrapers.FaceAppsScraper;

public class App {

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    new FaceAppsScraper().scrape();
  }
}
