/*
 * This source file was generated by the Gradle 'init' task
 */
package me.eeshe.watchfacescraper;

import java.util.List;

import me.eeshe.watchfacescraper.database.SQLiteManager;
import me.eeshe.watchfacescraper.model.Watchface;
import me.eeshe.watchfacescraper.model.scrapers.FaceAppsScraper;
import me.eeshe.watchfacescraper.service.WatchfaceService;

public class App {

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    SQLiteManager sqLiteManager = new SQLiteManager();
    WatchfaceService watchfaceService = new WatchfaceService(sqLiteManager);
    watchfaceService.createTables();

    List<Watchface> watchfaces = new FaceAppsScraper().scrape();
    watchfaceService.writeWatchfaces(watchfaces);
  }
}
